SystemOrganization addCategory: #NewWave!
SystemOrganization addCategory: #'NewWave-Announcers'!
SystemOrganization addCategory: #'NewWave-Core'!
SystemOrganization addCategory: #'NewWave-Engine'!
SystemOrganization addCategory: #'NewWave-Example'!
SystemOrganization addCategory: #'NewWave-Model'!
SystemOrganization addCategory: #'NewWave-Tests'!
SystemOrganization addCategory: #'NewWave-Visualization'!
